# Generated by Django 3.0.5 on 2020-04-21 10:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='created_on',
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='WorkflowSteps',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True, unique=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=350)),
                ('workflow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowsteps', to='api.Workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
