# Generated by Django 3.0.5 on 2020-04-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200421_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ('id',), 'verbose_name': 'Workflow', 'verbose_name_plural': 'Workflows'},
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(max_length=350, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='workflowsteps',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='workflowsteps',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
    ]
