# Python CircleCI 2.0 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/app

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: Add python project to path
          command: 'echo "$(realpath .)/app" > venv/lib/python3.8/site-packages/app.pth'
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test app
  deploy-job:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Deploy via Fabric
          command: |
            sudo pip install fabric==1.14.0
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              fab -f .circleci/deploy.py -i ~/.ssh/id_rsa production deploy
            else
              fab -f .circleci/deploy.py -i ~/.ssh/id_rsa staging deploy
            fi
